{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="element">
{"Users that will get notified"|i18n("design/standard/workflow/eventtype/view")}:

{section var=user loop=$event.approve_users}
    {delimiter}, {/delimiter}
    {fetch( content, object, hash( object_id, $user.item ) ).name|wash}
{/section}
</div>

<div class="element">
{"Monitored objects"|i18n("design/standard/workflow/eventtype/view")}:

{section var=user loop=$event.approve_groups}
    {delimiter}, {/delimiter}
    {fetch( content, object, hash( object_id, $user.item ) ).name|wash}
{/section}
</div>