    <li id="id_{literal}{$id}{/literal}_{literal}{$position}{/literal}" class="ui-state-default answerelement">
        <input class="parentID" type="hidden" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][parentID]" value="{literal}{$id}{/literal}" />
        <input type="hidden" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][id]" value="{literal}{$answerID}{/literal}" />
        <input type="hidden" class="answerPosition" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][position]" value="{literal}{$position}{/literal}" />
        Richtig: <input type="checkbox" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][correct]" /><br />
        Antwort:<br /> <textarea name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][text]" rows="2" cols="20" {literal}{$readOnly}{/literal} onchange="removeOnChange({literal}{$id}{/literal})">{literal}{$answer_text}{/literal}</textarea><br />
        Punkte:<br /> <input type="text" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][points]" value="{literal}{$answer_points}{/literal}" title="{'Diese Punktzahl wird vergeben, sobald diese Antwort richtig beantwortet wurde.'|i18n('xrowquestionnaire/datatype/edit')}" /><br />
        Bildverknüpfung:<br /> <input type="text" id="xrowquestionnaire_{$contentobject_id}_{$version}_images_{$attrID}_{literal}{$id}{/literal}_{literal}{$position}{/literal}_relation" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][object_relation]" value="" />
        <button class="button uploadImage" type="button" name="{$attribute_base}_xrowquestionnaire[{$attrID}][questions][{literal}{$id}{/literal}][answers][{literal}{$position}{/literal}][image]" id="xrowquestionnaire_{$contentobject_id}_{$version}_images_{$attrID}_{literal}{$id}{/literal}_{literal}{$position}{/literal}">Bild hinzufügen</button><br />
        <input type="hidden" id="xrowquestionnaire_{$contentobject_id}_{$version}_images_{$attrID}_{literal}{$id}_{$position}{/literal}_url" value={concat( 'questionnaire/upload/', $contentobject_id, '/', $version, '/images' )|ezurl()} />
        <button class="button" type="button" onclick="removeAnswer({literal}{$id},{$position}{/literal});">Antwort entfernen</button>
    </li>